
obj-y += nuc970_cap.o
obj-$(CONFIG_SENSOR_OV7725) += sensor_ov7725.o
obj-$(CONFIG_SENSOR_OV5640) += sensor_ov5640.o
obj-$(CONFIG_SENSOR_NT99141) += sensor_nt99141.o
obj-$(CONFIG_SENSOR_NT99050) += sensor_nt99050.o

