# NUC970 series audio
snd-soc-nuc970-pcm-objs := nuc970-pcm.o
snd-soc-nuc970-i2s-objs := nuc970-i2s.o

obj-$(CONFIG_SND_SOC_NUC970) += snd-soc-nuc970-pcm.o nuc970-i2s.o

# Boards
snd-soc-nuc970-audio-objs := nuc970-audio.o

obj-$(CONFIG_SND_SOC_NUC970EVB) += snd-soc-nuc970-audio.o
